import { get } from 'node-emoji';

export const EMOJIS = {
  HEART: get('heart'),
  TWO_HEARTS: get('two_hearts'),
  COFFEE: get('coffee'),
  BEER: get('beer'),
  BROKEN_HEART: get('broken_heart'),
  CRYING: get('crying_cat_face'),
  HEART_EYES: get('heart_eyes_cat'),
  JOY: get('joy_cat'),
  KISSING: get('kissing_cat'),
  SCREAM: get('scream_cat'),
  ROCKET: get('rocket'),
  SMIRK: get('smirk_cat'),
  RAISED_HANDS: get('raised_hands'),
  POINT_RIGHT: get('point_right'),
  ZAP: get('zap'),
  BOOM: get('boom'),
  PRAY: get('pray'),
  WINE: get('wine_glass'),
  MAG: get('mag'),
  HEAVY_CHECK_MARK: get('heavy_check_mark'),
  HEAVY_MULTIPLICATION_X: get('heavy_multiplication_x'),
  ROBOT_FACE: get('robot_face'),
  MONEY_WITH_WINGS: get('money_with_wings'),
  TIMER: get('⏳'),
  DOOR: get('🚪'),
  USER: get('👤'),
  KEY: get('🔑'),
};
